config/routes.rb
Rails.application.routes.draw do
  resources :tipo_docs
  resources :prod_servis
  resources :operacoes_faturas
  resources :pagamentos
  devise_for :users
  resources :utilizadors
  get 'login/index'

  resources :conta_bancaria
	resources :moedas
	resources :bancos
	resources :entidades
	resources :bairros
	resources :municipios
	resources :provincia
	resources :tipo_entidades
	root 'login#index'
	get 'inicio' => 'pagina_inicial#inicial'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bairro.rb
class Bairro < ApplicationRecord
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/conta_bancarium.rb
class ContaBancarium < ApplicationRecord
end

app/models/entidade.rb
class Entidade < ApplicationRecord
	
	has_attached_file :asset, :styles => { :medium => "400x400>", :thumb => "100x100>" }
	validates_presence_of :nome, message: 'não pode ser deixado em branco'
	validates_length_of :nome, minimum: 2, message: 'deve ter pelo menos 3 caracteres'
	validates_uniqueness_of :nome, message: 'Esta entidade já existe'
	mount_uploader :foto, FotoUploader
end

app/models/moeda.rb
class Moeda < ApplicationRecord
end

app/models/municipio.rb
class Municipio < ApplicationRecord
end

app/models/operacoes_fatura.rb
class OperacoesFatura < ApplicationRecord
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
end

app/models/prod_servi.rb
class ProdServi < ApplicationRecord
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/tipo_doc.rb
class TipoDoc < ApplicationRecord
end

app/models/tipo_entidade.rb
class TipoEntidade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/utilizador.rb
class Utilizador < ApplicationRecord
end

app/controllers/tipo_entidades_controller.rb
class TipoEntidadesController < ApplicationController
  before_action :set_tipo_entidade, only: [:show, :edit, :update, :destroy]

  # GET /tipo_entidades
  # GET /tipo_entidades.json
  def index
    @tipo_entidades = TipoEntidade.all
  end

  # GET /tipo_entidades/1
  # GET /tipo_entidades/1.json
  def show
  end

  # GET /tipo_entidades/new
  def new
    @tipo_entidade = TipoEntidade.new
  end

  # GET /tipo_entidades/1/edit
  def edit
  end

  # POST /tipo_entidades
  # POST /tipo_entidades.json
  def create
    @tipo_entidade = TipoEntidade.new(tipo_entidade_params)

    respond_to do |format|
      if @tipo_entidade.save
        format.html { redirect_to @tipo_entidade, notice: 'Tipo entidade was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_entidade }
      else
        format.html { render :new }
        format.json { render json: @tipo_entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_entidades/1
  # PATCH/PUT /tipo_entidades/1.json
  def update
    respond_to do |format|
      if @tipo_entidade.update(tipo_entidade_params)
        format.html { redirect_to @tipo_entidade, notice: 'Tipo entidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_entidade }
      else
        format.html { render :edit }
        format.json { render json: @tipo_entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_entidades/1
  # DELETE /tipo_entidades/1.json
  def destroy
    @tipo_entidade.destroy
    respond_to do |format|
      format.html { redirect_to tipo_entidades_url, notice: 'Tipo entidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_entidade
      @tipo_entidade = TipoEntidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_entidade_params
      params.require(:tipo_entidade).permit(:descricao, :codigo)
    end
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/helpers/tipo_docs_helper.rb
module TipoDocsHelper
end

app/helpers/tipo_entidades_helper.rb
module TipoEntidadesHelper
end

app/views/tipo_entidades/_form.html.erb
<%= form_for(tipo_entidade) do |f| %>
  <% if tipo_entidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_entidade.errors.count, "error") %> prohibited this tipo_entidade from being saved:</h2>

      <ul>
      <% tipo_entidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>
    <div class="field">
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_entidades/edit.html.erb
<h1>Editing Tipo Entidade</h1>

<%= render 'form', tipo_entidade: @tipo_entidade %>

<%= link_to 'Show', @tipo_entidade %> |
<%= link_to 'Back', tipo_entidades_path %>

app/views/tipo_entidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Entidades</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_entidades.each do |tipo_entidade| %>
      <tr>
        <td><%= tipo_entidade.descricao %></td>
        <td><%= tipo_entidade.codigo %></td>
        <td><%= link_to 'Show', tipo_entidade %></td>
        <td><%= link_to 'Edit', edit_tipo_entidade_path(tipo_entidade) %></td>
        <td><%= link_to 'Destroy', tipo_entidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Entidade', new_tipo_entidade_path %>

app/views/tipo_entidades/new.html.erb
<h1>New Tipo Entidade</h1>

<%= render 'form', tipo_entidade: @tipo_entidade %>

<%= link_to 'Back', tipo_entidades_path %>

app/views/tipo_entidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo_entidade.descricao %>
</p>
<p>
  <strong>Codigo:</strong>
  <%= @tipo_entidade.codigo %>
</p>

<%= link_to 'Edit', edit_tipo_entidade_path(@tipo_entidade) %> |
<%= link_to 'Back', tipo_entidades_path %>