config/routes.rb
Rails.application.routes.draw do
  resources :tipo_docs
  resources :prod_servis
  resources :operacoes_faturas
  resources :pagamentos
  devise_for :users
  resources :utilizadors
  get 'login/index'

  resources :conta_bancaria
	resources :moedas
	resources :bancos
	resources :entidades
	resources :bairros
	resources :municipios
	resources :provincia
	resources :tipo_entidades
	root 'login#index'
	get 'inicio' => 'pagina_inicial#inicial'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bairro.rb
class Bairro < ApplicationRecord
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/conta_bancarium.rb
class ContaBancarium < ApplicationRecord
end

app/models/entidade.rb
class Entidade < ApplicationRecord
	
	has_attached_file :asset, :styles => { :medium => "400x400>", :thumb => "100x100>" }
	validates_presence_of :nome, message: 'não pode ser deixado em branco'
	validates_length_of :nome, minimum: 2, message: 'deve ter pelo menos 3 caracteres'
	validates_uniqueness_of :nome, message: 'Esta entidade já existe'
	mount_uploader :foto, FotoUploader
end

app/models/moeda.rb
class Moeda < ApplicationRecord
end

app/models/municipio.rb
class Municipio < ApplicationRecord
end

app/models/operacoes_fatura.rb
class OperacoesFatura < ApplicationRecord
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
end

app/models/prod_servi.rb
class ProdServi < ApplicationRecord
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/tipo_doc.rb
class TipoDoc < ApplicationRecord
end

app/models/tipo_entidade.rb
class TipoEntidade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/utilizador.rb
class Utilizador < ApplicationRecord
end

app/controllers/entidades_controller.rb
class EntidadesController < ApplicationController
  before_action :set_entidade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /entidades
  # GET /entidades.json
  def index
    @entidades = Entidade.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  # GET /entidades/1
  # GET /entidades/1.json
  def show
  end

  # GET /entidades/new
  def new
    @entidade = Entidade.new
  end

  # GET /entidades/1/edit
  def edit
  end

  # POST /entidades
  # POST /entidades.json
  def create
    @entidade = Entidade.new(entidade_params)

    respond_to do |format|
      if @entidade.save
        format.html { redirect_to @entidade, notice: 'Entidade was successfully created.' }
        format.json { render :show, status: :created, location: @entidade }
      else
        format.html { render :new }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entidades/1
  # PATCH/PUT /entidades/1.json
  def update
    respond_to do |format|
      if @entidade.update(entidade_params)
        format.html { redirect_to @entidade, notice: 'Entidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @entidade }
      else
        format.html { render :edit }
        format.json { render json: @entidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entidades/1
  # DELETE /entidades/1.json
  def destroy
    @entidade.destroy
    respond_to do |format|
      format.html { redirect_to entidades_url, notice: 'Entidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entidade
      @entidade = Entidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entidade_params
      params.require(:entidade).permit(:nome, :bi, :provincia_id, :municipio_id, :bairro_id, :pai, :mae, :nif, :tipoEntidade, :nacionalidade, :profissao, :genero, :estadoCivil, :telefone, :email, :homePage, :estado, :foto)
    end
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/helpers/tipo_docs_helper.rb
module TipoDocsHelper
end

app/views/entidades/_form.html.erb
<style type="text/css">
  input[type=text]{
    width: 90%;
  }
  #entidade_provincia_id{
    float: left;
  }
  #entidade_municipio_id{
    float: left;
  }
  #entidade_bairro_id{
    float: left;
  }
</style>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Dados Pessoais</div>
      <div class="panel-body" style="position:relative;margin:0; ">
        <%= simple_form_for entidade, as: 'entidade', :multipart => true  do |f| %>

        <%= f.input(:nome, label: 'Nome da Entidade', has_validators: false) %>

        <%= f.label :genero, style: "float: left;"%> 
        <%= f.label :estadoCivil, style: "float: left; margin-left: 40px"%>  
        <br>
        <br>
        <%= f.select(:genero,options_for_select([["Masculino", "M"], ["Femenino", "F"]],entidade.genero), {include_blank: "Selecione"}) %>

        
        <%= f.select(:estadoCivil,options_for_select(['Solteiro/a','Casado/a','Divorciado/a','Viuvo/a'],entidade.estadoCivil), {include_blank: "Selecione"}) %>

        <%= f.input :bi, label: 'Bilhete de Identidade', placeholder: "" %>



        <%= f.input :nacionalidade, label: 'nacionalidade', placeholder: "" %>
        <%= f.label :provincia_id, style: "float: left"  %> 
        <%= f.label :municipio_id, style: "float: left; margin-left: 40px; margin-button:5px;"  %>
        <%= f.label :bairro_id, style: "float: left; margin-left: 40px" %>

        <br><br>

        <%= f.collection_select(:provincia_id, Provincium.all, :id, :descricao, prompt: false) %>


        <%= f.collection_select(:municipio_id, Municipio.all, :id, :descricao, prompt: false) %>


        <%= f.collection_select(:bairro_id, Bairro.all, :id, :descricao, prompt: false) %>


        <br><br>
        <%= f.input :pai, label: 'Nome Pai', placeholder: "" %>
        <%= f.input :mae, label: 'Nome Mãe', placeholder: "" %>

        


      </div>
    </div>

  </div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Dados Profissionais</div>
      <div class="panel-body" style="position:relative;margin:0; ">
      
        <%= f.file_field :foto %>
        <%= f.input :nif, label: 'Nº do NIF', placeholder: "" %>
        <%= f.input :profissao, label: 'Profissão', placeholder: "" %>

        <%= f.label :telefone %>
        <%= f.text_field :telefone %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :tipoEntidade %>
        <%= f.collection_select(:tipoEntidade, TipoEntidade.all, :id, :descricao, {include_blank: "Selecione"}, prompt: true) %>

        <%= f.label :homePage %>
        <%= f.number_field :homePage %>

        <%= f.label :estado %>
        <%= f.select(:estado,options_for_select(['Activo','Inactivo'],entidade.estado), {include_blank: "Selecione"}) %>

        <br>
        <br>
        

        

      </div>
    </div>

  </div>
</div>

<div class="col-md-12">
 <div class="panel panel-primary">
  <div class="panel-body" style="position:relative;margin:0; ">
    <%= f.button :submit, "Concluir" , class: "btn btn-primary", style: "float:left" %>

    <% end %>

app/views/entidades/edit.html.erb
<h1>Editing Entidade</h1>

<%= render 'form', entidade: @entidade %>

<%= link_to 'Show', @entidade %> |
<%= link_to 'Back', entidades_path %>

app/views/entidades/index.html.erb
<div class="col-md-12">
 <div class="panel panel-primary">
  <div class="panel-body" style="position:relative;margin:0; ">
    <%= link_to new_entidade_path, class: "btn btn-default btn-info" do %>
    <i class="fa fa-plus"></i> Nova Entidade
    
    <% end %>
  </div>
</div>
</div>

<p id="notice"><%= notice %></p>

<div class="panel panel-default"> <div class="panel-heading">
  <h3>Listagem de Entidades</h3>
</div> 
<div class="table-responsive">
  <table class="table"> 
    <thead>
      <tr>
        <th>Nome</th>
        <th>Bi</th>
        <th>Bairro</th>
        <th>Nif</th>
        <th>Tipo entidade</th>
        <th>Profissao</th>
        <th>Genero</th>
        <th>Telefone</th>
        <th>Homepage</th>
        <th>Estado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @entidades.each do |entidade| %>
      <tr>
        <td><%= entidade.nome %></td>
        <td><%= entidade.bi %></td>
        <td><%= entidade.bairro_id %></td>
        <td><%= entidade.nif %></td>
        <td><%= TipoEntidade.find(entidade.tipoEntidade).descricao %></td>
        <td><%= entidade.profissao %></td>
        <td><%= entidade.genero %></td>
        <td><%= entidade.telefone %></td>
        <td><%= entidade.homePage %></td>
        <td><%= entidade.estado %></td>
        <td><%= link_to 'Mostrar', entidade, class: "label label-info" %></td>
        <td><%= link_to 'Editar', edit_entidade_path(entidade), class: "label label-warning" %></td>
        <td><%= link_to 'Eliminar', entidade, method: :delete, data: { confirm: 'Tem certeza ?' }, class: "label label-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>
<div style="float: right;">
<%= will_paginate( @entidades, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Próxima") %></div>
  
</div>

<br>

app/views/entidades/new.html.erb
<h3>Nova Entidade</h3>

<%= render 'form', entidade: @entidade %>

<%= link_to 'Back', entidades_path, class:"btn btn-warning" %>
</div>
</div>
</div>

app/views/entidades/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Dados Pessoais</div>
      <div class="panel-body" style="position:relative;margin:0; ">


        <p>
          <strong>Nome:</strong>
          <%= @entidade.nome %>
        </p>

        <p>
          <strong>Bi:</strong>
          <%= @entidade.bi %>
        </p>

        <p>
          <strong>Genero:</strong>
          <%= @entidade.genero %>
        </p>

        <p>
          <strong>Estadocivil:</strong>
          <%= @entidade.estadoCivil %>
        </p>
        <p>
          <strong>Nacionalidade:</strong>
          <%= @entidade.nacionalidade %>
        </p>

        <p>
          <strong>Provincia:</strong>
          <%= Provincium.find(@entidade.provincia_id).descricao %>
        </p>

        <p>
          <strong>Municipio:</strong>
          <%= Municipio.find(@entidade.municipio_id).descricao %>
        </p>

        <p>
          <strong>Bairro:</strong>
          <%= Bairro.find(@entidade.bairro_id).descricao %>
        </p>

        <p>
          <strong>Pai:</strong>
          <%= @entidade.pai %>
        </p>

        <p>
          <strong>Mae:</strong>
          <%= @entidade.mae %>
        </p>

      </div>
    </div>

  </div>

  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Dados Profissionais</div>
      <div class="panel-body" style="position:relative;margin:0; ">
      <%= image_tag(@entidade.foto_url, size: "150x150") if @entidade.foto? %>
        <p>
          <strong>Nif:</strong>
          <%= @entidade.nif %>
        </p>

        <p>
          <strong>Tipoentidade:</strong>
          <%= TipoEntidade.find(@entidade.tipoEntidade).descricao %>
        </p>


        <p>
          <strong>Profissao:</strong>
          <%= @entidade.profissao %>
        </p>


        <p>
          <strong>Telefone:</strong>
          <%= @entidade.telefone %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @entidade.email %>
        </p>

        <p>
          <strong>Homepage:</strong>
          <%= @entidade.homePage %>
        </p>

        <p>
          <strong>Estado:</strong>
          <%= @entidade.estado %>
        </p>
      </div>
    </div>

  </div>
</div>
<%= link_to 'Editar', edit_entidade_path(@entidade) %> |
<%= link_to 'Voltar', entidades_path %>