config/routes.rb
Rails.application.routes.draw do
  resources :tipo_docs
  resources :prod_servis
  resources :operacoes_faturas
  resources :pagamentos
  devise_for :users
  resources :utilizadors
  get 'login/index'

  resources :conta_bancaria
	resources :moedas
	resources :bancos
	resources :entidades
	resources :bairros
	resources :municipios
	resources :provincia
	resources :tipo_entidades
	root 'login#index'
	get 'inicio' => 'pagina_inicial#inicial'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bairro.rb
class Bairro < ApplicationRecord
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/conta_bancarium.rb
class ContaBancarium < ApplicationRecord
end

app/models/entidade.rb
class Entidade < ApplicationRecord
	
	has_attached_file :asset, :styles => { :medium => "400x400>", :thumb => "100x100>" }
	validates_presence_of :nome, message: 'não pode ser deixado em branco'
	validates_length_of :nome, minimum: 2, message: 'deve ter pelo menos 3 caracteres'
	validates_uniqueness_of :nome, message: 'Esta entidade já existe'
	mount_uploader :foto, FotoUploader
end

app/models/moeda.rb
class Moeda < ApplicationRecord
end

app/models/municipio.rb
class Municipio < ApplicationRecord
end

app/models/operacoes_fatura.rb
class OperacoesFatura < ApplicationRecord
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
end

app/models/prod_servi.rb
class ProdServi < ApplicationRecord
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/tipo_doc.rb
class TipoDoc < ApplicationRecord
end

app/models/tipo_entidade.rb
class TipoEntidade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/utilizador.rb
class Utilizador < ApplicationRecord
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: [:show, :edit, :update, :destroy]

  # GET /pagamentos
  # GET /pagamentos.json
  def index
    @pagamentos = Pagamento.all.order("created_at DESC").paginate(page: params[:page], per_page: 5)
  end

  # GET /pagamentos/1
  # GET /pagamentos/1.json
  def show
  end

  # GET /pagamentos/new
  def new
    @pagamento = Pagamento.new
  end

  # GET /pagamentos/1/edit
  def edit
  end

  # POST /pagamentos
  # POST /pagamentos.json
  def create
    @pagamento = Pagamento.new(pagamento_params)

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully created.' }
        format.json { render :show, status: :created, location: @pagamento }
      else
        format.html { render :new }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagamentos/1
  # PATCH/PUT /pagamentos/1.json
  def update
    respond_to do |format|
      if @pagamento.update(pagamento_params)
        format.html { redirect_to @pagamento, notice: 'Pagamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @pagamento }
      else
        format.html { render :edit }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1
  # DELETE /pagamentos/1.json
  def destroy
    @pagamento.destroy
    respond_to do |format|
      format.html { redirect_to pagamentos_url, notice: 'Pagamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagamento
      @pagamento = Pagamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pagamento_params
      params.require(:pagamento).permit(:codigo, :formaPagamento, :banco_id, :conta_bancaria_id, :numeroTalao, :dataPagamento, :valorTalao, :valorUtilizado)
    end
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/helpers/tipo_docs_helper.rb
module TipoDocsHelper
end

app/views/pagamentos/_form.html.erb
<%= simple_form_for pagamento, as: 'pagamento', :multipart => true  do |f| %>
<%= f.error_notification %>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Dados Pessoais</div>
      <div class="panel-body" style="position:relative;margin:0; ">


        <%= f.input(:codigo, label: 'Codigo de pagamento', has_validators: false) %>

        <%= f.label :formaPagamento, style: "float: left;"%> 


        <br>
        <br>
        <%= f.select(:formaPagamento,options_for_select([["Deposito Bancário", "Deposito Bancário"], ["Transferência Bancaria", "Transferência Bancaria"], ["Cash", "Cash"]],pagamento.formaPagamento), {include_blank: "Selecione"}) %>
        <br><br>
        <%= f.label :banco_id, style: "float: left;"%> 
        <br><br>
        <%= f.collection_select(:banco_id, Banco.all, :id, :descricao, prompt: false) %>
        <br><br>
        <%= f.label :conta_bancaria_id, style: "float: left;"%>
        <br><br>
        <%= f.collection_select(:conta_bancaria_id, ContaBancarium.all, :id, :descricao, prompt: false) %>
        <%= f.input :numeroTalao, label: 'Número de talão', placeholder: "" %>

        <br>
        <%= f.input :dataPagamento, label: "Data pagamento", as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y'), type: "date" } %>  
        <%= f.input :valorTalao, label: 'Valor Talão', placeholder: "" %>
        <%= f.input :valorUtilizado, label: 'Valor Utilizado', placeholder: "" %>

      </div>
    </div>

  </div>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/pagamentos/edit.html.erb
<h1>Editar Pagamento</h1>

<%= render 'form', pagamento: @pagamento %>

<%= link_to 'Show', @pagamento %> |
<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/index.html.erb
<div class="col-md-12">
 <div class="panel panel-primary">
  <div class="panel-body" style="position:relative;margin:0; ">
    <%= link_to new_pagamento_path, class: "btn btn-default btn-info" do %>
    <i class="fa fa-plus"></i> Novo Pagamento
    
    <% end %>
  </div>
</div>
</div>
<p id="notice"><%= notice %></p>

<div class="panel panel-default"> <div class="panel-heading">
  <h3>Listagem de Entidades</h3>
</div> 
<div class="table-responsive">
  <table class="table"> 
    <thead>
      <tr>
        <th>Codigo</th>
        <th>Formapagamento</th>
        <th>Banco</th>
        <th>Conta bancaria</th>
        <th>Numerotalao</th>
        <th>Datapagamento</th>
        <th>Valortalao</th>
        <th>Valorutilizado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pagamentos.each do |pagamento| %>
      <tr>

        <td><%= pagamento.codigo %></td>
        <td><%= pagamento.formaPagamento %></td>
        <td><%= pagamento.banco_id %></td>
        <td><%= pagamento.conta_bancaria_id %></td>
        <td><%= pagamento.numeroTalao %></td>
        <td><%= pagamento.dataPagamento %></td>
        <td><%= pagamento.valorTalao %></td>
        <td><%= pagamento.valorUtilizado %></td>
        <td><%= link_to 'Mostrar', pagamento, class: "label label-info" %></td>
        <td><%= link_to 'Editar', edit_pagamento_path(pagamento), class: "label label-warning" %></td>
        <td><%= link_to 'Eliminar', pagamento, method: :delete, data: { confirm: 'Tem certeza ?' }, class: "label label-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>
<div style="float: right;">
  <%= will_paginate( @pagamentos, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Próxima") %></div>
  
</div>

<br>

<br>

app/views/pagamentos/new.html.erb
<h1>Novo Pagamento</h1>

<%= render 'form', pagamento: @pagamento %>

<%= link_to 'Back', pagamentos_path %>

app/views/pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @pagamento.codigo %>
</p>

<p>
  <strong>Formapagamento:</strong>
  <%= @pagamento.formaPagamento %>
</p>

<p>
  <strong>Banco:</strong>
  <%= @pagamento.banco_id %>
</p>

<p>
  <strong>Conta bancaria:</strong>
  <%= @pagamento.conta_bancaria_id %>
</p>

<p>
  <strong>Numerotalao:</strong>
  <%= @pagamento.numeroTalao %>
</p>

<p>
  <strong>Datapagamento:</strong>
  <%= @pagamento.dataPagamento %>
</p>

<p>
  <strong>Valortalao:</strong>
  <%= @pagamento.valorTalao %>
</p>

<p>
  <strong>Valorutilizado:</strong>
  <%= @pagamento.valorUtilizado %>
</p>

<%= link_to 'Edit', edit_pagamento_path(@pagamento) %> |
<%= link_to 'Back', pagamentos_path %>