config/routes.rb
Rails.application.routes.draw do
  resources :tipo_docs
  resources :prod_servis
  resources :operacoes_faturas
  resources :pagamentos
  devise_for :users
  resources :utilizadors
  get 'login/index'

  resources :conta_bancaria
	resources :moedas
	resources :bancos
	resources :entidades
	resources :bairros
	resources :municipios
	resources :provincia
	resources :tipo_entidades
	root 'login#index'
	get 'inicio' => 'pagina_inicial#inicial'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bairro.rb
class Bairro < ApplicationRecord
end

app/models/banco.rb
class Banco < ApplicationRecord
end

app/models/conta_bancarium.rb
class ContaBancarium < ApplicationRecord
end

app/models/entidade.rb
class Entidade < ApplicationRecord
	
	has_attached_file :asset, :styles => { :medium => "400x400>", :thumb => "100x100>" }
	validates_presence_of :nome, message: 'não pode ser deixado em branco'
	validates_length_of :nome, minimum: 2, message: 'deve ter pelo menos 3 caracteres'
	validates_uniqueness_of :nome, message: 'Esta entidade já existe'
	mount_uploader :foto, FotoUploader
end

app/models/moeda.rb
class Moeda < ApplicationRecord
end

app/models/municipio.rb
class Municipio < ApplicationRecord
end

app/models/operacoes_fatura.rb
class OperacoesFatura < ApplicationRecord
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
end

app/models/prod_servi.rb
class ProdServi < ApplicationRecord
end

app/models/provincium.rb
class Provincium < ApplicationRecord
end

app/models/tipo_doc.rb
class TipoDoc < ApplicationRecord
end

app/models/tipo_entidade.rb
class TipoEntidade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/utilizador.rb
class Utilizador < ApplicationRecord
end

app/controllers/bairros_controller.rb
class BairrosController < ApplicationController
  before_action :set_bairro, only: [:show, :edit, :update, :destroy]

  # GET /bairros
  # GET /bairros.json
  def index
    @bairros = Bairro.all
  end

  # GET /bairros/1
  # GET /bairros/1.json
  def show
  end

  # GET /bairros/new
  def new
    @bairro = Bairro.new
  end

  # GET /bairros/1/edit
  def edit
  end

  # POST /bairros
  # POST /bairros.json
  def create
    @bairro = Bairro.new(bairro_params)

    respond_to do |format|
      if @bairro.save
        format.html { redirect_to @bairro, notice: 'Bairro was successfully created.' }
        format.json { render :show, status: :created, location: @bairro }
      else
        format.html { render :new }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bairros/1
  # PATCH/PUT /bairros/1.json
  def update
    respond_to do |format|
      if @bairro.update(bairro_params)
        format.html { redirect_to @bairro, notice: 'Bairro was successfully updated.' }
        format.json { render :show, status: :ok, location: @bairro }
      else
        format.html { render :edit }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bairros/1
  # DELETE /bairros/1.json
  def destroy
    @bairro.destroy
    respond_to do |format|
      format.html { redirect_to bairros_url, notice: 'Bairro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bairro
      @bairro = Bairro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bairro_params
      params.require(:bairro).permit(:descricao, :codigo, :municipio_id)
    end
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/helpers/bancos_helper.rb
module BancosHelper
end

app/helpers/entidades_helper.rb
module EntidadesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/moedas_helper.rb
module MoedasHelper
end

app/helpers/municipios_helper.rb
module MunicipiosHelper
end

app/helpers/provincia_helper.rb
module ProvinciaHelper
end

app/helpers/tipo_docs_helper.rb
module TipoDocsHelper
end

app/views/bairros/_form.html.erb
<style type="text/css">
  input[type=text]{
    width: 90%;
  }

</style>
<div class="row">
<div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Rigisto de bairros</div>
      <div class="panel-body" style="position:relative;margin:0; ">
        <%= simple_form_for bairro, as: 'bairro'  do |f| %>
       

        <%= f.input(:descricao, label: 'Descrição', placeholder: "Porfavor verifique o caompo") %>
       
        
        <%= f.input :codigo, label: 'Codigo', placeholder: "Porfavor, digite o codigo" %>
        <%= f.label :municipio_id %>
        <%= f.collection_select(:municipio_id, Municipio.all, :id, :descricao, prompt: true) %>

        <br>
        <br>
        <br>
        <%= f.button :submit, "Concluir" , class: "btn btn-primary" %>

        <% end %>

      </div>
    </div>
    
  </div>

</div>

app/views/bairros/edit.html.erb
<h1>Edição Bairro</h1>

<%= render 'form', bairro: @bairro %>

<%= link_to 'Show', @bairro, class: "btn btn-info" %> |
<%= link_to 'Back',  bairros_path, class: "btn btn-danger" %>

app/views/bairros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bairros</h1>
<div class="panel panel-default"> <div class="panel-heading">Listagem</div> <table class="table"> 
<thead> 
  <tr>
    <th>Cod.</th>
    <th>Descricao</th>
    <th>Codigo Bairro</th>
    <th>Municipio</th>
    <th colspan="3"></th>
  </tr>
</thead> 
<tbody> 
  <% a=0 %>
  <% @bairros.each do |bairro| %>
  <tr>
    <td><%= a+=1 %></td>
    <td><%= bairro.descricao %></td>
    <td><%= bairro.codigo %></td>
    <td><%= Municipio.find(bairro.municipio_id).descricao  %></td>
    <td><%= link_to 'Mostrar', bairro %></td>
    <td><%= link_to 'Editar', edit_bairro_path(bairro) %></td>
    <td><%= link_to 'Eliminar', bairro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</tbody> </table> 
</div>

<br>

<%= link_to 'New Bairro', new_bairro_path %>

app/views/bairros/new.html.erb
<h1>Novo Bairro</h1>

<%= render 'form', bairro: @bairro %>
<div class="col-md-6">

<%= link_to 'Back', bairros_path , class: "btn btn-danger" %>
</div>

app/views/bairros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<div class="row">
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">Dados do Bairro</div>
				<div class="panel-body" style="position:relative;margin:0; ">
					<h4><span class="label label-default">Descricao:</span> <%= @bairro.descricao %></h4>

				</p>
				<p>
					<h4><span class="label label-default">Codigo:</span> <%= @bairro.codigo %></h4>

				</p>
				<p>
					<h4><span class="label label-default">Municipio:</span> <%= Municipio.find(@bairro.municipio_id).descricao %></h4>

				</p>
			</div>
		</div>
	</div>
</div>


<%= link_to 'Edit', edit_bairro_path(@bairro),class: "btn btn-info" %> |
<%= link_to 'Back', bairros_path, class: "btn btn-danger" %>